"""
Django settings for backend project.
Generated by 'django-admin startproject' using Django 5.1.4.
For more information, refer to:
https://docs.djangoproject.com/en/5.1/topics/settings/
"""

from pathlib import Path

# === PATH CONFIGURATION ===
BASE_DIR = Path(__file__).resolve().parent.parent

# === SECURITY SETTINGS ===
SECRET_KEY = "django-insecure-%8klce4s7z!hs$ej@a5d967@jj1km64+a7z-1l7rlfln#-au!g"  # IMPORTANT: Keep secret key safe
DEBUG = True  # WARNING: Set to False in production
ALLOWED_HOSTS = []  # Example: ['your-domain.com']

# === APPLICATION CONFIGURATION ===
# Core Django apps
DJANGO_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

# Local apps
LOCAL_APPS = [
    'QuizzMaster.apps.QuizzmasterConfig',
]

INSTALLED_APPS = DJANGO_APPS + LOCAL_APPS

# === MIDDLEWARE CONFIGURATION ===
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# === URLS/WGI CONFIGURATION ===
ROOT_URLCONF = "backend.urls"
WSGI_APPLICATION = "backend.wsgi.application"

# === TEMPLATE SETTINGS ===
TEMPLATE_DIRS = [BASE_DIR / "templates"]  # Custom template directory path

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": TEMPLATE_DIRS,
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# === DATABASE CONFIGURATION ===
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "quizz",  # Database name
        "USER": "root",  # MySQL Username
        "PASSWORD": "",  # MySQL Password
        "HOST": "127.0.0.1",  # Host address
        "PORT": "3306",  # Port number
    }
}

# === PASSWORD VALIDATION SETTINGS ===
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# === INTERNATIONALIZATION SETTINGS ===
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# === STATIC FILES SETTINGS ===
STATIC_URL = "static/"

# === DEFAULT PRIMARY KEY FIELD TYPE ===
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"